/**
 * Generates the secrets required by backend/src/config/env.ts.
 *
 *   node scripts/generate-secrets.mjs
 *
 * Prints ready-to-paste values. Nothing is written to disk automatically —
 * the output is the secret, and a script that silently rewrites your .env is a
 * script that will eventually commit one.
 */
import { randomBytes } from 'node:crypto';

const b64 = (bytes) => randomBytes(bytes).toString('base64');

const secrets = {
  // Signs access tokens. 48 bytes -> 64 base64 chars.
  JWT_SECRET: b64(48),
  // AES-256-GCM key for connector credentials (Phase 4). Must be exactly 32
  // bytes decoded, so it is emitted as hex rather than base64.
  CREDENTIALS_MASTER_KEY: randomBytes(32).toString('hex'),
};

console.log('# Generated by scripts/generate-secrets.mjs — do not commit these values.\n');
for (const [key, value] of Object.entries(secrets)) {
  console.log(`${key}=${key === 'CREDENTIALS_MASTER_KEY' ? value : `"${value}"`}`);
}
console.log('\n# Store these in your secret manager or a gitignored .env on the VPS.');
